### ISSUE TITLE
Support CDN urls via unpkg.com

### ISSUE THREAD

**Issue by fahad19** [Travix-International/travix-ui-kit#8]
Once you publish a package to npm, content of the package is available via https://unpkg.com.

So once you publish `travix-ui-kit` to npm, the dist could be loaded with a `<script>` tag for example:

```html
<script src="https://unpkg.com/travix-ui-kit@0.x/dist/travix-ui-kit.min.js"></script>
```

Similar thing was done for `frint` too: https://github.com/Travix-International/frint/pull/59

**Comment by mAiNiNfEcTiOn** [comment]
Good idea, but the problem is that the UI-Kit package is something you install to generate your ui-kit bundle. It's not the final product.

_Why?_, you may ask... During the UI Kit's development some decisions were made point to the direction of having a base/default layout on this project, but that could be overwritten. 

Some inner parts of the system depend on specifications done in a spec file (YAML, JS, ...), which - when overwritten - need to re-build the ui-bundle.css again to have the right values.

Last but not the least, there were also _business-related_ decisions on it such as "the designers prefer to set variables' values in a YAML file as it's easier for them".

Nevertheless I would also like of something as a final product in the `dist` folder that would be overwritten using the already existing CSS engine and it's cascading features.

Maybe the feature request could be closed and opened a new one in that direction?

_just my 2 cents, though_

**Comment by asci** [comment]
if we're not considering themes as private travix data - we can add them to repo of UI-Kit and extend build (publish) process with generation all theme files for all brands and countries combinations. Otherwise, we can prebuild default theme

And about YAML, I'm not really sure that designers team will edit these files on a regular base and we can convince them to use a different format. One of reason to choose YAML was to restrict ourselves and don't logic into data, but still be able to reuse some definitions. If we'll find that YAML doesn't perfectly suit our needs, we can easily switch to JS-objects (or any other format for our needs).

**Comment by asci** [comment]
apart from this, what value it will bring to our project? Are we using some CDNs for currently used libraries (such as React\lodash)? Even for development, it would be better to have it locally. I consider UI-kit more as a building tool, like webpack or so, you put some data in, and then use result  where you what

**Comment by fahad19** [comment]
> I consider UI-kit more as a building tool

I was considering it to be a finished product that is ready for consumption (with default theme applied).

I will close this issue then. Thanks for explaining 👍
